//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsAttendanceWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int PersonId { get; set; }
        public string RecordBookNumber { get; set; }
        public System.DateTime BirthDate { get; set; }
        public Nullable<int> GroupId { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Person Person { get; set; }
    }
}
